### ISSUE TITLE
Add module for response headers

### ISSUE THREAD

**Issue by d-strobel** [d-strobel/ansible-collection-windows-adfs#9]
Add a module for response headers:

Example usage:
```
win_adfs_response_header:
  cors_trusted_origins:
    - https://example.com
    - https://example.de
  ...
  state: present
```

Powershell functions to use:
- Get-AdfsResponseHeaders
- Set-AdfsResponseHeaders
